_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10000
#max_steps: 150000
log_every_n_steps : 100
reload_dataloaders_every_n_epochs: 1
accelerator: gpu
# strategy: ddp_find_unused_parameters_true
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 10000

# set True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

#accumulate_grad_batches: 4