_target_: src.models.rl_module.DQNLightning


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  weight_decay: 1e-3

num_fcs: ${num_fcs}

net:
  _target_: src.models.components.dqn_nn.BranchDuelingDQNMulti
  obs_size: 18  # State space
  n_actions: 20  # Action space
  num_fcs: ${num_fcs}
  hidden_size: 256
  middle_size1: 128
  middle_size2: 64
  out_size: 32

target_net:
  _target_: src.models.components.dqn_nn.BranchDuelingDQNMulti
  obs_size: 18
  n_actions: 20
  num_fcs: ${num_fcs}
  hidden_size: 256
  middle_size1: 128
  middle_size2: 64
  out_size: 32

#env: CartPole-v1


env:
#  _target_: gym.make
  id: 'MultiFC_OT-v0'
  env_cfg:
    item_nbr: ${item_nbr}
    data_dir: ${paths.data_dir}/item_id_${item_nbr}/
    holding_cost: 1
    shortage_cost: 20
#    fc_lt_mean: 5
#    fc_lt_var: 1
#    lt_ecdfs: [(1, 0.1), (2, 0.3), (3, 0.6), (4, 0.9), (5, 1.0)]
    sel_FCs: [4270, 6284, 6753]
#    sel_FCs: [4270,  4270,  6284, 6753] #  6284,  6753,  7439, 7490,  7728,  8302]
    num_fcs: ${num_fcs}
    num_sku: 1
    forecast_horizon: 100
    starting_week: 12351


seed: ${seed}

#buffer:
#  _target_: src.data.components.replay_buffer.ReplayBuffer
#  capacity: 1_000_000 # size of the buffer

agent_config:
  action_low: 0
  action_high: 3
  action_segment: 0.15
  act_dim: 3
  sub_act_dim: 20

capacity: 1_000_000 # size of the buffer
warm_start_steps: 10_000
dataset_sample_size: 256

# Agent
eps_start: 1.0
eps_end: 0.01
eps_last_frame: 43_500


sync_rate: 300
lr: 0.007378528457548085
gamma: 0.9
batch_size: ${batch_size}
log_fc_metrics: False