_target_: src.models.rl_module.DQNLightning


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  weight_decay: 1e-3


net:
  _target_: src.models.components.dqn_nn.DQN
  obs_size: 4  # for CartPole-v1
  n_actions: 2  # for CartPole-v1
  hidden_size: 128

target_net:
  _target_: src.models.components.dqn_nn.DQN
  obs_size: 4  # for CartPole-v1
  n_actions: 2  # for CartPole-v1
  hidden_size: 128

#env: CartPole-v1
env:
  _target_: gym.make
  id: 'MultiSKU-v0'
  env_cfg:
    item_nbr: ${item_nbr}
    data_dir: ${paths.data_dir}/item_id_${item_nbr}/
    holding_cost: 0.1
    shortage_cost: 1.0
    fc_lt_mean: [5]
    fc_lt_var: [1]
    num_fc: 1
    num_sku: 1
    forecast_horizon: 100
    starting_week: 12351

env:
#  _target_: gym.make
  id: 'DummyEnv-v0'
  env_cfg:
    item_nbr: 8645745
    max_steps: 200
    state_size: 4
    action_size: 2

seed: 3407 #${seed}

buffer:
  _target_: src.data.components.replay_buffer.ReplayBuffer
  capacity: 1000 # size of the buffer


warm_start_steps: 1000
episode_length: 200

# Agent
eps_start: 1.0
eps_end: 0.01
eps_last_frame: 1000


sync_rate: 10
lr: 1e-2
gamma: 0.99
batch_size: 150 #${batch_size}